[[redirects]]
  from = "https://anonymouslocker.app/*"
  to = "https://anonshop.anonindustries.com/:splat"
  status = 301
  force = true # COMMENT: ensure that we always redirect
[[redirects]]
  from = "https://anonshop.app/*"
  to = "https://anonshop.anonindustries.com/:splat"
  status = 301
  force = true # COMMENT: ensure that we always redirect
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
[functions]
  included_files = ["./netlify/functions/bip39Wordlist.txt", "/netlify/functions/bip39Wordlist.txt" ]