[[redirects]]
  from = "http://anonymouslocker.app/*"
  to = " https://www.anonshop.app/:splat"
  status = 301
  force = true # COMMENT: ensure that we always redirect
[[redirects]]
  from = "/*"
  to = "/"
  status = 200